const GET_EVENT_TYPE_START = 'entertainments/GET_EVENT_TYPE_START';
const GET_EVENT_TYPE_SUCCESS = 'entertainments/GET_EVENT_TYPE_SUCCESS';
const GET_EVENT_TYPE_FAIL = 'entertainments/GET_EVENT_TYPE_FAIL';

const GET_EVENT_INFO_START = 'entertainments/GET_EVENT_INFO_START';
const GET_EVENT_INFO_SUCCESS = 'entertainments/GET_EVENT_INFO_SUCCESS';
const GET_EVENT_INFO_FAIL = 'entertainments/GET_EVENT_INFO_FAIL';

const GET_EVENT_REQUESTS_START = 'entertainments/GET_EVENT_REQUESTS_START';
const GET_EVENT_REQUESTS_SUCCESS = 'entertainments/GET_EVENT_REQUESTS_SUCCESS';
const GET_EVENT_REQUESTS_FAIL = 'entertainments/GET_EVENT_REQUESTS_FAIL';

const CLEAR_EVENT_REQUESTS_SUCCESS = 'entertainments/CLEAR_EVENT_REQUESTS_SUCCESS';

const CREATE_COMPANY_EVENT_START = 'entertainments/CREATE_COMPANY_EVENT_START';
const CREATE_COMPANY_EVENT_SUCCESS = 'entertainments/CREATE_COMPANY_EVENT_SUCCESS';
const CREATE_COMPANY_EVENT_FAIL = 'entertainments/CREATE_COMPANY_EVENT_FAIL';
const CREATE_EVENT_DATE_START = 'entertainments/CREATE_EVENT_DATE_START';
const CREATE_EVENT_DATE_SUCCESS = 'entertainments/CREATE_EVENT_DATE_SUCCESS';
const CREATE_EVENT_DATE_FAIL = 'entertainments/CREATE_EVENT_DATE_FAIL';
const CHANGE_COMPANY_EVENT_START = 'entertainments/CHANGE_COMPANY_EVENT_START';
const CHANGE_COMPANY_EVENT_SUCCESS = 'entertainments/CHANGE_COMPANY_EVENT_SUCCESS';
const CHANGE_COMPANY_EVENT_FAIL = 'entertainments/CHANGE_COMPANY_EVENT_FAIL';
const CHANGE_EVENT_DATE_START = 'entertainments/CHANGE_EVENT_DATE_START';
const CHANGE_EVENT_DATE_SUCCESS = 'entertainments/CHANGE_EVENT_DATE_SUCCESS';
const CHANGE_EVENT_DATE_FAIL = 'entertainments/CHANGE_EVENT_DATE_FAIL';

const GET_EVENT_REQUEST_START = 'entertainments/GET_EVENT_REQUEST_START';
const GET_EVENT_REQUEST_FAIL = 'entertainments/GET_EVENT_REQUEST_FAIL';

export {
  GET_EVENT_TYPE_START,
  GET_EVENT_TYPE_SUCCESS,
  GET_EVENT_TYPE_FAIL,
  GET_EVENT_INFO_START,
  GET_EVENT_INFO_SUCCESS,
  GET_EVENT_INFO_FAIL,
  GET_EVENT_REQUESTS_START,
  GET_EVENT_REQUESTS_SUCCESS,
  GET_EVENT_REQUESTS_FAIL,
  CLEAR_EVENT_REQUESTS_SUCCESS,
  CREATE_COMPANY_EVENT_START,
  CREATE_COMPANY_EVENT_SUCCESS,
  CREATE_COMPANY_EVENT_FAIL,
  CREATE_EVENT_DATE_START,
  CREATE_EVENT_DATE_SUCCESS,
  CREATE_EVENT_DATE_FAIL,
  CHANGE_COMPANY_EVENT_START,
  CHANGE_COMPANY_EVENT_SUCCESS,
  CHANGE_COMPANY_EVENT_FAIL,
  CHANGE_EVENT_DATE_START,
  CHANGE_EVENT_DATE_SUCCESS,
  CHANGE_EVENT_DATE_FAIL,
  GET_EVENT_REQUEST_START,
  GET_EVENT_REQUEST_FAIL,
};
