const UPLOAD_IMAGE_START = 'files/UPLOAD_IMAGE_START';
const UPLOAD_IMAGE_SUCCESS = 'files/UPLOAD_IMAGE_SUCCESS';
const UPLOAD_FAILURE = 'files/UPLOAD_FAILURE';

export {
  UPLOAD_IMAGE_START,
  UPLOAD_IMAGE_SUCCESS,
  UPLOAD_FAILURE,
};
