const GET_ALL_COMPANY_START = 'admin/GET_ALL_COMPANY_START';
const GET_ALL_COMPANY_SUCCESS = 'admin/GET_ALL_COMPANY_SUCCESS';
const GET_ALL_COMPANY_FAIL = 'admin/GET_GET_ALL_COMPANY_FAIL';

const GET_ALL_EVENTS_START = 'admin/GET_ALL_EVENTS_START';
const GET_ALL_EVENTS_SUCCESS = 'admin/GET_ALL_EVENTS_SUCCESS';
const GET_ALL_EVENTS_FAIL = 'admin/GET_ALL_EVENTS_FAIL';

const DELETE_EVENT_START = 'admin/DELETE_EVENT_START';
const DELETE_EVENT_SUCCESS = 'admin/DELETE_EVENT_SUCCESS';
const DELETE_EVENT_FAIL = 'admin/DELETE_EVENT_FAIL';

const GET_ALL_USERS_START = 'admin/GET_ALL_USERS_START';
const GET_ALL_USERS_SUCCESS = 'admin/GET_ALL_USERS_SUCCESS';
const GET_ALL_USERS_FAIL = 'admin/GET_ALL_USERS_FAIL';

const CREATE_EVENT_TYPE_START = 'admin/CREATE_EVENT_TYPE_START';
const CREATE_EVENT_TYPE_SUCCESS = 'admin/CREATE_EVENT_TYPE_SUCCESS';
const CREATE_EVENT_TYPE_FAIL = 'admin/CREATE_EVENT_TYPE_FAIL';

const CHANGE_USER_ROLE_START = 'admin/CHANGE_USER_ROLE_START';
const CHANGE_USER_ROLE_SUCCESS = 'admin/CHANGE_USER_ROLE_SUCCESS';
const CHANGE_USER_ROLE_FAIL = 'admin/CHANGE_USER_ROLE_FAIL';

const CHANGE_COMPANY_START = 'admin/CHANGE_COMPANY_START';
const CHANGE_COMPANY_SUCCESS = 'admin/CHANGE_COMPANY_SUCCESS';
const CHANGE_COMPANY_FAIL = 'admin/CHANGE_COMPANY_FAIL';

const CHANGE_EVENT_TYPE_START = 'admin/CHANGE_EVENT_TYPE_START';
const CHANGE_EVENT_TYPE_SUCCESS = 'admin/CHANGE_EVENT_TYPE_SUCCESS';
const CHANGE_EVENT_TYPE_FAIL = 'admin/CHANGE_EVENT_TYPE_FAIL';

export {
  GET_ALL_COMPANY_SUCCESS,
  GET_ALL_COMPANY_START,
  GET_ALL_COMPANY_FAIL,
  GET_ALL_EVENTS_START,
  GET_ALL_EVENTS_SUCCESS,
  GET_ALL_EVENTS_FAIL,
  DELETE_EVENT_START,
  DELETE_EVENT_SUCCESS,
  DELETE_EVENT_FAIL,
  GET_ALL_USERS_START,
  GET_ALL_USERS_SUCCESS,
  GET_ALL_USERS_FAIL,
  CHANGE_USER_ROLE_START,
  CHANGE_USER_ROLE_SUCCESS,
  CHANGE_USER_ROLE_FAIL,
  CHANGE_COMPANY_START,
  CHANGE_COMPANY_SUCCESS,
  CHANGE_COMPANY_FAIL,
  CREATE_EVENT_TYPE_START,
  CREATE_EVENT_TYPE_SUCCESS,
  CREATE_EVENT_TYPE_FAIL,
  CHANGE_EVENT_TYPE_START,
  CHANGE_EVENT_TYPE_SUCCESS,
  CHANGE_EVENT_TYPE_FAIL,
};
