const GET_COMPANY_INFO_START = 'company/GET_COMPANY_INFO_START';
const GET_COMPANY_INFO_SUCCESS = 'company/GET_COMPANY_INFO_SUCCESS';
const GET_COMPANY_INFO_FAIL = 'company/GET_COMPANY_INFO_FAIL';

const GET_SELECTED_COMPANY_START = 'company/GET_SELECTED_COMPANY_START';
const GET_SELECTED_COMPANY_SUCCESS = 'company/GET_SELECTED_COMPANY_SUCCESS';
const GET_SELECTED_COMPANY_FAIL = 'company/GET_SELECTED_COMPANY_FAIL';

const GET_COMPANY_EVENTS_START = 'company/GET_COMPANY_EVENTS_START';
const GET_COMPANY_EVENTS_SUCCESS = 'company/GET_COMPANY_EVENTS_SUCCESS';
const GET_COMPANY_EVENTS_FAIL = 'company/GET_COMPANY_EVENTS_FAIL';

const GET_ONE_COMPANY_REVIEWS_START = 'company/GET_ONE_COMPANY_REVIEWS_START';
const GET_ONE_COMPANY_REVIEWS_SUCCESS = 'company/GET_ONE_COMPANY_REVIEWS_SUCCESS';
const GET_ONE_COMPANY_REVIEWS_FAIL = 'company/GET_ONE_COMPANY_REVIEWS_FAIL';

const CREATE_COMPANY_REVIEWS_START = 'company/CREATE_COMPANY_REVIEWS_START';
const CREATE_COMPANY_REVIEWS_SUCCESS = 'company/CREATE_COMPANY_REVIEWS_SUCCESS';
const CREATE_COMPANY_REVIEWS_FAIL = 'company/CREATE_COMPANY_REVIEWS_FAIL';

const CREATE_COMPANY_START = 'company/CREATE_COMPANY_START';
const CREATE_COMPANY_SUCCESS = 'company/CREATE_COMPANY_SUCCESS';
const CREATE_COMPANY_FAIL = 'company/CREATE_COMPANY_FAIL';

const CHANGE_COMPANY_START = 'company/CHANGE_COMPANY_START';
const CHANGE_COMPANY_SUCCESS = 'company/CHANGE_COMPANY_SUCCESS';
const CHANGE_COMPANY_FAIL = 'company/CHANGE_COMPANY_FAIL';

export {
  GET_COMPANY_INFO_SUCCESS,
  GET_COMPANY_INFO_START,
  GET_COMPANY_INFO_FAIL,
  GET_COMPANY_EVENTS_START,
  GET_COMPANY_EVENTS_SUCCESS,
  GET_COMPANY_EVENTS_FAIL,
  GET_SELECTED_COMPANY_START,
  GET_SELECTED_COMPANY_SUCCESS,
  GET_SELECTED_COMPANY_FAIL,
  GET_ONE_COMPANY_REVIEWS_START,
  GET_ONE_COMPANY_REVIEWS_SUCCESS,
  GET_ONE_COMPANY_REVIEWS_FAIL,
  CREATE_COMPANY_REVIEWS_START,
  CREATE_COMPANY_REVIEWS_SUCCESS,
  CREATE_COMPANY_REVIEWS_FAIL,
  CREATE_COMPANY_START,
  CREATE_COMPANY_SUCCESS,
  CREATE_COMPANY_FAIL,
  CHANGE_COMPANY_START,
  CHANGE_COMPANY_SUCCESS,
  CHANGE_COMPANY_FAIL,
};
