const REMOVE_TOKEN = 'auth/REMOVE_TOKEN';
const LOGIN_START = 'auth/LOGIN_START';
const LOGIN_SUCCESS = 'auth/LOGIN_SUCCESS';
const LOGIN_FAIL = 'auth/LOGIN_FAIL';
const SIGNUP_START = 'auth/SIGNUP_START';
const SIGNUP_SUCCESS = 'auth/SIGNUP_SUCCESS';
const SIGNUP_FAIL = 'auth/SIGNUP_FAIL';
const CHECK_AUTHORIZATION = 'auth/CHECK_AUTHORIZATION';

export {
  REMOVE_TOKEN,
  LOGIN_FAIL,
  LOGIN_START,
  LOGIN_SUCCESS,
  SIGNUP_START,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
  CHECK_AUTHORIZATION,
};
