const LOGOUT_SUCCESS = 'user/LOGOUT_SUCCESS';

const GET_USER_INFO_START = 'user/GET_USER_INFO_START';
const GET_USER_INFO_SUCCESS = 'user/GET_USER_INFO_SUCCESS';
const GET_USER_INFO_FAIL = 'user/GET_USER_INFO_FAIL';

export {
  LOGOUT_SUCCESS,
  GET_USER_INFO_SUCCESS,
  GET_USER_INFO_START,
  GET_USER_INFO_FAIL,
};
