import type { AppProps } from 'next/app';
import Head from 'next/head';
import React from 'react';
import { Provider } from 'react-redux';
import wrapper from 'src/redux/store';
import 'src/styles/stylesheet.css';
import 'src/styles/globals.scss';

export default function App({ Component, ...rest }: AppProps): JSX.Element {
  const { store, props } = wrapper.useWrappedStore(rest);
  /*  const { dispatch = () => {}, getState = () => ({}) } = store;
  const propsStore = getState();
  const {
    auth: { token } = {},
  } = propsStore || {}; */

  return (
    <>
      <Head>
        <title>АтмосфераСити</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" type="image/x-icon" href="/icons-сube-gradient-96.png" />
      </Head>
      <Provider store={store}>
        <Component {...props.pageProps} />
      </Provider>
    </>
  );
}

App.getInitialProps = wrapper
  .getInitialPageProps((store) => async (context) => {});
